force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Store information from Countrylayer</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>alpha2Code__c</fullName>
    <description>Country alpha2Code</description>
    <inlineHelpText>Country alpha2Code</inlineHelpText>
    <label>alpha2Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>alpha3Code__c</fullName>
    <description>Country alpha3Code</description>
    <inlineHelpText>Country alpha3Code</inlineHelpText>
    <label>alpha3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/capital__c.field-meta.xml
<CustomField>
    <fullName>capital__c</fullName>
    <label>Capital</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Regional_Blocs__c.field-meta.xml
<CustomField>
    <fullName>Regional_Blocs__c</fullName>
    <label>Regional Blocs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WTO_acronyms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>alpha2Code__c</fullName>
    <label>Country Alpha 2 Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>alpha3Code__c</fullName>
    <label>Country Alpha 3 Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/capital__c.field-meta.xml
<CustomField>
    <fullName>capital__c</fullName>
    <label>Country Capital</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Country Region</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Regional_Blocs__c.field-meta.xml
<CustomField>
    <fullName>Regional_Blocs__c</fullName>
    <label>Country Regional Blocs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WTO_acronyms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/WTO_acronyms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CACM</fullName>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
    </customValue>
    <customValue>
        <fullName>CARICOM</fullName>
    </customValue>
    <customValue>
        <fullName>CEMAC</fullName>
    </customValue>
    <customValue>
        <fullName>COMESA</fullName>
    </customValue>
    <customValue>
        <fullName>EAC</fullName>
    </customValue>
    <customValue>
        <fullName>EACU</fullName>
    </customValue>
    <customValue>
        <fullName>EEA</fullName>
    </customValue>
    <customValue>
        <fullName>EU</fullName>
    </customValue>
    <customValue>
        <fullName>EUCU</fullName>
    </customValue>
    <customValue>
        <fullName>GCC</fullName>
    </customValue>
    <customValue>
        <fullName>CH-FL</fullName>
    </customValue>
    <customValue>
        <fullName>MERCOSUR</fullName>
    </customValue>
    <customValue>
        <fullName>SACU</fullName>
    </customValue>
    <customValue>
        <fullName>UK-CD</fullName>
    </customValue>
    <customValue>
        <fullName>WAEMU</fullName>
    </customValue>
    <masterLabel>WTO acronyms</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CountryTriggerHandler.cls
/**
 * @author David Fernandez
 * @date 05.09.2023
 *
 * @description Handler for Country__c Trigger
 */
public with sharing class CountryTriggerHandler {

    @TestVisible
    private LeadSelector leadSelectorImpl{
        get{
            if(leadSelectorImpl == null){
                leadSelectorImpl = new LeadSelector();
            }
            return leadSelectorImpl;
        }
        set;
    }
    public void updateRelatedLeads(List<Country__c> countries){
        List<Lead> updatedLeads =  new List<Lead>();
        for(Country__c country:countries){
            Set<String> possibleCountryNames = new Set<String>{
                    country.Name,country.alpha2Code__c,country.alpha3Code__c
            };
            List<Lead> foundLeads = leadSelectorImpl.selectByCountryNames(possibleCountryNames);
            for(Lead lead:foundLeads){
                lead.alpha2Code__c = country.alpha2Code__c;
                lead.alpha3Code__c = country.alpha3Code__c;
                lead.capital__c = country.capital__c;
                lead.Region__c = country.Region__c;
                lead.Regional_Blocs__c = country.Regional_Blocs__c;
            }
            updatedLeads.addAll(foundLeads);
        }
        if(updatedLeads.size()>0){
            update updatedLeads;
        }
    }
}