force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Store information from Countrylayer</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>alpha2Code__c</fullName>
    <description>Country alpha2Code</description>
    <inlineHelpText>Country alpha2Code</inlineHelpText>
    <label>alpha2Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>alpha3Code__c</fullName>
    <description>Country alpha3Code</description>
    <inlineHelpText>Country alpha3Code</inlineHelpText>
    <label>alpha3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/capital__c.field-meta.xml
<CustomField>
    <fullName>capital__c</fullName>
    <label>Capital</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryLayer_API__mdt/CountryLayer_API__mdt.object-meta.xml
<CustomObject>
    <label>CountryLayer API</label>
    <pluralLabel>CountryLayer APIs</pluralLabel>
</CustomObject>

force-app/main/default/objects/CountryLayer_API__mdt/fields/API_KEY__c.field-meta.xml
<CustomField>
    <fullName>API_KEY__c</fullName>
    <label>API KEY</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CountryLayerSelector_Test.cls
/**
 * @author David Fernandez
 * @date 02.09.2023.
 *
 * @description Test for the selector class
 */

@IsTest
private class CountryLayerSelector_Test {
    @IsTest
    private static void selectApiKeyByNameTest(){
        //Mocks
        //Given
        String environment = 'Development';

        //When
        Test.startTest();
        CountryLayer_API__mdt api = new CountryLayerSelector().selectApiKeyByName(environment);
        Test.stopTest();

        //Then
        System.assertNotEquals(null, api.API_KEY__c,'No value found in metadata');
    }

    @IsTest
    private static void selectExistingCountriesTest(){
        //Mocks
        //Given
        new SObjectBuilder(Country__c.SObjectType)
        .put(Country__c.Name,'Czech Republic')
        .put(Country__c.alpha2Code__c,'CZ')
        .put(Country__c.alpha3Code__c,'CZE')
        .put(Country__c.capital__c,'Prague')
        .create();

        //When
        Test.startTest();
        List<Country__c> existingCountries = new CountryLayerSelector().selectExistingCountries();
        Test.stopTest();

        //Then
        System.assertEquals(1, existingCountries.size(),'Different amount found in the database');
    }

}