force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Store information from Countrylayer</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>alpha2Code__c</fullName>
    <description>Country alpha2Code</description>
    <inlineHelpText>Country alpha2Code</inlineHelpText>
    <label>alpha2Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>alpha3Code__c</fullName>
    <description>Country alpha3Code</description>
    <inlineHelpText>Country alpha3Code</inlineHelpText>
    <label>alpha3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/capital__c.field-meta.xml
<CustomField>
    <fullName>capital__c</fullName>
    <label>Capital</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Regional_Blocs__c.field-meta.xml
<CustomField>
    <fullName>Regional_Blocs__c</fullName>
    <label>Regional Blocs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WTO_acronyms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CountryLayer_API__mdt/CountryLayer_API__mdt.object-meta.xml
<CustomObject>
    <label>CountryLayer API</label>
    <pluralLabel>CountryLayer APIs</pluralLabel>
</CustomObject>

force-app/main/default/objects/CountryLayer_API__mdt/fields/API_KEY__c.field-meta.xml
<CustomField>
    <fullName>API_KEY__c</fullName>
    <label>API KEY</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/WTO_acronyms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CACM</fullName>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
    </customValue>
    <customValue>
        <fullName>CARICOM</fullName>
    </customValue>
    <customValue>
        <fullName>CEMAC</fullName>
    </customValue>
    <customValue>
        <fullName>COMESA</fullName>
    </customValue>
    <customValue>
        <fullName>EAC</fullName>
    </customValue>
    <customValue>
        <fullName>EACU</fullName>
    </customValue>
    <customValue>
        <fullName>EEA</fullName>
    </customValue>
    <customValue>
        <fullName>EU</fullName>
    </customValue>
    <customValue>
        <fullName>EUCU</fullName>
    </customValue>
    <customValue>
        <fullName>GCC</fullName>
    </customValue>
    <customValue>
        <fullName>CH-FL</fullName>
    </customValue>
    <customValue>
        <fullName>MERCOSUR</fullName>
    </customValue>
    <customValue>
        <fullName>SACU</fullName>
    </customValue>
    <customValue>
        <fullName>UK-CD</fullName>
    </customValue>
    <customValue>
        <fullName>WAEMU</fullName>
    </customValue>
    <masterLabel>WTO acronyms</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CountryLayerSelector.cls
/**
 * @author David Fernandez
 * @date 01.09.2023
 */
public with sharing class CountryLayerSelector {
    public CountryLayer_API__mdt selectApiKeyByName(String label){
        return [SELECT API_KEY__c FROM CountryLayer_API__mdt WHERE MasterLabel =:label LIMIT 1];
    }

    public List<Country__c> selectExistingCountries(){
        return [SELECT Id, Name, alpha2Code__c, alpha3Code__c, capital__c, Region__c, Regional_Blocs__c FROM Country__c];
    }
}