force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Store information from Countrylayer</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>alpha2Code__c</fullName>
    <description>Country alpha2Code</description>
    <inlineHelpText>Country alpha2Code</inlineHelpText>
    <label>alpha2Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>alpha3Code__c</fullName>
    <description>Country alpha3Code</description>
    <inlineHelpText>Country alpha3Code</inlineHelpText>
    <label>alpha3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/capital__c.field-meta.xml
<CustomField>
    <fullName>capital__c</fullName>
    <label>Capital</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>alpha2Code__c</fullName>
    <label>Country Alpha 2 Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>alpha3Code__c</fullName>
    <label>Country Alpha 3 Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/capital__c.field-meta.xml
<CustomField>
    <fullName>capital__c</fullName>
    <label>Country Capital</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Country Region</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CountryTriggerHandler_Test.cls
/**
 * Created by david on 05.09.2023.
 */
@IsTest
private class CountryTriggerHandler_Test {
    @IsTest
    private static void updateRelatedLeadsTest(){
        //Given
        Country__c czechCountry = (Country__c) new SObjectBuilder(Country__c.SObjectType)
                .put(Country__c.Name, 'Czech Republic')
                .put(Country__c.alpha2Code__c, 'CZ')
                .put(Country__c.alpha3Code__c, 'CZE')
                .put(Country__c.capital__c, 'Prague')
                .put(Country__c.Region__c, 'Europe')
                .build().getRecord();

        Lead relatedLead = (Lead)new SObjectBuilder(Lead.SObjectType)
                .put(Lead.LastName,'Test')
                .put(Lead.Company,'Test')
                .put(Lead.Status,'Open - Not Contacted')
                .put(Lead.Country,'CZE')
                .create().getRecord();

        //Mocks
        GenericStub stub = new GenericStub();
        stub = stub.forMethod('selectByCountryNames')
                .thatReturns(new List<Lead>{relatedLead});

        LeadSelector selectorMock = (LeadSelector) Test.createStub(LeadSelector.class, stub);
        CountryTriggerHandler handler = new CountryTriggerHandler();
        handler.leadSelectorImpl = selectorMock;

        //When
        Test.startTest();
            handler.updateRelatedLeads(new List<Country__c>{czechCountry});
        Test.stopTest();

        //Then
        Lead modifiedRecord = [SELECT alpha3Code__c FROM Lead WHERE Id = :relatedLead.Id];
        System.assertEquals(czechCountry.alpha3Code__c, modifiedRecord.alpha3Code__c,'Change didn\'t happen');
    }
}