force-app/main/default/objects/Lead/fields/alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>alpha2Code__c</fullName>
    <label>Country Alpha 2 Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>alpha3Code__c</fullName>
    <label>Country Alpha 3 Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/capital__c.field-meta.xml
<CustomField>
    <fullName>capital__c</fullName>
    <label>Country Capital</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Country Region</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadSelector_Test.cls
/**
 * Created by david on 05.09.2023.
 */
@IsTest
private class LeadSelector_Test {
    @IsTest
    private static void selectByCountryNamesTest(){
        //Given
        new SObjectBuilder(Lead.SObjectType)
                .put(Lead.LastName,'Test')
                .put(Lead.Company,'Test')
                .put(Lead.Status,'Open - Not Contacted')
                .put(Lead.alpha2Code__c,'CZ')
                .put(Lead.alpha3Code__c,'CZE')
                .put(Lead.capital__c,'Prague')
                .put(Lead.Region__c,'Europe')
                .put(Lead.Country,'CZE')
                .create();
        Set<String> nameSet = new Set<String>{
                'Czech Republic',
                'CZ',
                'CZE'
        };

        //When
        Test.startTest();
            List<Lead> foundLeads = new LeadSelector().selectByCountryNames(nameSet);
        Test.stopTest();

        //Then
        System.assertEquals(1,foundLeads.size(),'Unexpected number of records found');
    }
}